
set(RISCV_GCC_PREFIX "${CMAKE_CURRENT_SOURCE_DIR}/../Toolchain/GCC/${RISCV_ARCH}")
set(RISCV_GCC_BASENAME "riscv32-unknown-elf")

set(RISCV_LLVM_PREFIX "${CMAKE_CURRENT_SOURCE_DIR}/../Toolchain/llvm/bin" CACHE PATH "Install location of LLVM RISC-V toolchain.")

set(TC_PREFIX "${RISCV_GCC_PREFIX}/bin/${RISCV_GCC_BASENAME}-")

set(CMAKE_C_COMPILER ${TC_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${TC_PREFIX}g++)
set(CMAKE_ASM_COMPILER ${TC_PREFIX}gcc)
set(CMAKE_LINKER ${TC_PREFIX}ld)
set(CMAKE_OBJCOPY ${TC_PREFIX}objcopy)
set(CMAKE_OBJDUMP ${TC_PREFIX}objdump)
set(CMAKE_AR ${TC_PREFIX}ar)
set(CMAKE_RANLIB ${TC_PREFIX}ranlib)
set(CMAKE_STRIP ${TC_PREFIX}strip)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=${RISCV_ARCH}_zicsr_zvl${MIN_VLEN}b -mabi=${RISCV_ABI} -mcmodel=${RISCV_CMODEL}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=${RISCV_ARCH}_zicsr_zvl${MIN_VLEN}b -mabi=${RISCV_ABI} -mcmodel=${RISCV_CMODEL}")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -march=${RISCV_ARCH}_zicsr_zvl${MIN_VLEN}b -mabi=${RISCV_ABI} -mcmodel=${RISCV_CMODEL}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -march=${RISCV_ARCH}_zicsr_zvl${MIN_VLEN}b -mabi=${RISCV_ABI} -mcmodel=${RISCV_CMODEL}")
